services:
  appbook:
    restart: always
    image: rafaelsenff/app-book:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=[x]
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/nginx/certificate/novocertificate.pfx
    ports:
      - 5001:80
      - 5002:443
    volumes:
      - /etc/nginx/certificate:/etc/nginx/certificate
    depends_on:
      - mongo
      - rabbitmq
  appbookhistory:
    restart: always
    image: rafaelsenff/app-bookhistory:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=[x]
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/nginx/certificate/novocertificate.pfx
    ports:
      - 5003:80
      - 5004:443
    volumes:
      - /etc/nginx/certificate:/etc/nginx/certificate
    depends_on:
      - mongo
      - rabbitmq
  appfrontend:
    restart: always
    image: rafaelsenff/app-frontend:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certificate:/etc/nginx/certificate
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongodbdata_volume:/data/db    
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: [x]
      MONGO_INITDB_ROOT_PASSWORD: [x]
  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
volumes:
  rabbitmq_data:
  rabbitmq_log:
  mongodbdata_volume:
    external: true